### PR TITLE
Updating to 0.23.0

### PR DESCRIPTION
**Pull request by signorecello**

### CODE REVIEW

**Review by critesjosh — APPROVED** [review]

**Review by critesjosh — CHANGES_REQUESTED** [review]
Actually looks like I hit errors when interacting with the UI. You can see in the preview

**Review by critesjosh — CHANGES_REQUESTED** [review]
I get the following error when running `npx hardhat node` and `yarn test`. 
image
I comment out the `accounts` defined in `hardhat.config.cts` and it works, but it's not immediately clear that's what should be done, or if that's what should be done.

And I am still seeing this error when trying to run the UI.

image

**Comment by signorecello** [comment]
Yeah that error is actually fine, again it is trying to read from a view function without passing any params. I can try to see if there's any wagmi option to not fetch automatically.

The other error is weird because I thought I had removed these configs from hardhat config. I'll do it today and finally push this over the line

**Review by critesjosh — CHANGES_REQUESTED** [review]
I didn't have metamask installed and there was indication that I need to in the web app. Maybe just add a note to the README.

I installed it and still see this error, so it's still not working for me. 
image

**Comment by signorecello** [comment]
So those logs aren't there anymore, I'm pretty sure you're getting a cached version of the page, or you didn't run `yarn build` in case you're running `yarn preview`. Can you double-check?

I'll change the README to make sure metamask is not mandatory

**Review by critesjosh — APPROVED** [review]

**Pull request merged**
