### PR TITLE
Submission to suggest a fix for issue : Add on-the-fly proof generation #26

### PR DESCRIPTION
**Pull request by bbresearcher**
# Description

## Problem\*
Submission to try help with a fix for issue : Add on-the-fly proof generation #26

Resolves 

## Summary\*
Added dynamic test code to `Starter.t.sol` in `test` directory.

## Additional Context

# PR Checklist\*

- [ x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by signorecello** [comment]
Thanks for your contribution @bbresearcher let me just run this CI and merge 😊

**Comment by bbresearcher** [comment]
Apologies for that, I have made changes to add ffi permissions by default in the foundry.toml file.

**Comment by critesjosh** [comment]
@bbresearcher Have you tested this in with multiple tests? 

@signorecello tried this earlier and there are some irresolvable race conditions (iirc) with writing to the Prover.toml with multiple tests. this can be resolved by running 1 test at a time I believe, you just might want to add that to the README.

**Comment by bbresearcher** [comment]
@critesjosh and @signorecello : I am trying to see if I can come up with a solution, my tests fail with 3 or 4 dynamic proof generations, I will test a few ways and then let you know if I was able to solve it, or if I am just going to add instructions in the README.

**Comment by bbresearcher** [comment]
Hi @critesjosh and @signorecello I have managed to find a way to resolve the race condition, please may I ask if you could verify that? I have cloned a clean version and followed the readme and it worked, I made sure my /tmp was cleaned of old artefacts as well.

**Comment by critesjosh** [comment]
Awesome! 🙌 I am on my phone but will test when I'm at my computer.

Just curious where you found the solution, do you have a link?

**Comment by bbresearcher** [comment]
@critesjosh I must be honest I came up with it by myself, I did not google anything.

**Comment by critesjosh** [comment]
Ah even better!

**Pull request merged**
